FROM golang:1.17-alpine3.14 AS build
RUN apk add --no-cache git
WORKDIR /app
COPY ./app /app
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:3.14
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=build /app/main .
COPY --from=build /app/.env .
EXPOSE 8080
CMD ["./main"]